version: '3.7'
services:

  postgres:
    image: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
